<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.6" />
  </ItemGroup>

  <!-- 引用星露谷的 MonoGame.Framework.dll（仅编译时使用，不复制到输出） -->
  <ItemGroup>
    <Reference Include="MonoGame.Framework">
      <HintPath>D:\Downloads\xlgwydnb_89472\SV.v1.6.15-0xdeadcode\MonoGame.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
