#ifndef ROTATING_ART_LAUNCHER_THREAD_AFFINITY_MANAGER_H
#define ROTATING_ART_LAUNCHER_THREAD_AFFINITY_MANAGER_H

int setThreadAffinityToBigCores();

#endif //ROTATING_ART_LAUNCHER_THREAD_AFFINITY_MANAGER_H
