set(BUILD_SDL3      OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(BUILD_UTILS     OFF CACHE BOOL "" FORCE)
set(BUILD_TESTS     OFF CACHE BOOL "" FORCE)
set(XNASONG         ON  CACHE BOOL "" FORCE)

set(SDL2_INCLUDE_DIRS ${LIBS_DIR}/SDL/include)
set(SDL2_LIBRARIES SDL2)

add_subdirectory(${LIBS_DIR}/FAudio)