set(BUILD_SDL3          OFF CACHE BOOL "" FORCE)
set(TRACING_SUPPORT     OFF CACHE BOOL "" FORCE)
set(BUILD_DXVK_NATIVE   OFF CACHE BOOL "" FORCE)

set(CMAKE_SKIP_INSTALL_RULES ON)
add_subdirectory(${LIBS_DIR}/FNA3D)
set(CMAKE_SKIP_INSTALL_RULES OFF)