set(SDL_VIDEO_OPENGL     ON CACHE BOOL "" FORCE)
set(SDL_VIDEO_OPENGL_ES ON CACHE BOOL "" FORCE)
set(SDL_VIDEO_OPENGL_EGL ON CACHE BOOL "" FORCE)
set(SDL_OPENGLES        ON CACHE BOOL "" FORCE)

add_compile_definitions(SDL_VIDEO_OPENGL_GL4ES)
add_subdirectory(${LIBS_DIR}/SDL)